* TODO Yadav and Michalak (2013) Kronecker products
* TODO Compare performance for different input chunk-sizes
  Doing everything in memory is only slightly slower, so there should
  be some optimum where caching is still good but I'm not spending so
  long building a huge dask graph and iterating through it.
* TODO Investigate nonzero increments for spatial structure
  R packages geostatsp, geoR, fields, and RandomFields would probably
  be useful
* TODO Check whether storing spectrum as a numpy array makes HomogeneousIsotropicCorrelations faster
  It may be re-calculating the weights on each trip through, which
  would be really slow.
* TODO test LinearOperator subclasses with other shapes
  Should this to work?
  Check the scipy-provided implementations:
  find one that doesn't delegate to :meth:`dot` or :meth:`solve`,
  which are designed to handle this case.
  If LinearOperator handles this, code can be simpler.
  If not, expand things to handle this and test that.
** LinearOperator[N, N].dot(array_like[..., N])
** LinearOperator[N, N].dot(array_like[..., N, K])
